source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'AFNetworking', '~> 2.5'
pod 'GoogleAnalytics-iOS-SDK'
pod 'MWPhotoBrowser', '~> 1.4'
pod 'REMenu'
pod 'Mantle'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SpinKit'
pod 'Harpy'
pod 'OpenInChrome'
pod 'SIAlertView'
pod 'RFRateMe', "~> 1.0.0"
pod 'iOS-Hierarchy-Viewer'
