source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
pod 'AFNetworking', '~> 2.4'
pod 'GoogleAnalytics-iOS-SDK'
pod 'MWPhotoBrowser', '~> 1.4'
pod 'REMenu'
pod 'Mantle'
pod 'UIActivityIndicator-for-SDWebImage'
pod 'SpinKit'
pod 'Harpy'
pod 'DZNEmptyDataSet'
